## Revisiting the LSTM

In [1]:
### importing the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import pandas_datareader as pdr
import os
from dotenv import load_dotenv

In [3]:
### importing the key
load_dotenv('../keys.txt')
key = os.getenv('key')

### Defining the functions and working with them

In [19]:
### targeting only the features ['close', 'high', 'low' and 'open']
features_to_target = ['close', 'high', 'low', 'open']

In [22]:
### function to load the stock price
def load_stock_price(symbol, features_to_target) : 

    df = pdr.get_data_tiingo(symbol, api_key = key)
    df = df[features_to_target].reset_index(drop = True)

    return df

In [23]:
stock_boeing = load_stock_price('BA', features_to_target)
stock_boeing.tail()

       close     high      low    open
1250  234.15  235.910  228.770  231.51
1251  232.44  236.450  232.065  234.99
1252  231.33  235.450  229.390  233.00
1253  230.72  231.330  227.070  231.05
1254  224.11  230.255  221.150  230.22

In [24]:
stock_apple = load_stock_price('AAPL', features_to_target)
stock_apple.tail()

       close    high     low     open
1250  273.43  275.77  271.65  275.045
1251  271.06  273.06  269.65  272.755
1252  267.61  268.36  265.07  266.090
1253  270.71  273.23  268.66  272.335
1254  270.17  271.04  267.04  267.550